### PR TITLE
Address GitHub issues #137, #99, #98, #96, #86

### LINKED ISSUE #86: Remove the json-rpc PINGs that initialize the GET /mcp sse stream
I added some PING notifications to the GET stream in order to unbreak some tests; however, this feels hacky and unnecessary. the PING notifications show up in the inspector, which might be confusing

### LINKED ISSUE #96: Log warnings when validation fails for elicitation schema projection
Follow on for #73 

https://github.com/fiberplane/mcp-lite/pull/73#discussion_r2382629727

### LINKED ISSUE #98: Add instructions on DNS rebinding protection, respond with json rpc message when headers invalid
Two things:

1. Add a section on DNS rebinding protection in the README
2. Return valid json rpc messages when the allowedHosts or allowedOrigins parameters block a request

## Adding DNS Rebinding Explanation to README

The spec and the [modelcontextprotocol/sdk](https://github.com/modelcontextprotocol/typescript-sdk/tree/main?tab=readme-ov-file#dns-rebinding-protection) make several mentions of DNS rebinding attacks, especially when running locally. There is a switch in their ts sdk:

```ts
const transport = new StreamableHTTPServerTransport({
  sessionIdGenerator: () => randomUUID(),
  enableDnsRebindingProtection: true,

  allowedHosts: ['127.0.0.1', ...],
  allowedOrigins: ['https://yourdomain.com', 'https://www.yourdomain.com']
});
```

We support allowed hosts and allowed origins already, which should be enough, but worth adding to the README.

As a note on the modelcontextprotocol sdk, disabling the flag `enableDnsRebindingProtection` just neglects to check headers entirely

https://github.com/modelcontextprotocol/typescript-sdk/blob/7d29cee2ba496212b2e074592da73b7cba7bee5c/src/server/streamableHttp.ts#L178 

## Returning JSON RPC when origin and host headers are not allowed

The modelcontextprotocol sdk responds with a json rpc message (see below), but right now we just do an http text response of Forbidden

```ts
      res.writeHead(403).end(JSON.stringify({
        jsonrpc: "2.0",
        error: {
          code: -32000,
          message: validationError
        },
        id: null
      }));
```

### LINKED ISSUE #99: Log warning (or throw error?) when a user binds an http transport multiple times to the same server
There is an easy way to shoot oneself in the foot with mcp-lite: If you repeatedly instantiate the streamable http transport and bind it to the same server multiple times, you can end up breaking a stateful server. The reason for this is that the transport overrides methods in the server to which it is bound for sending notifications and sending requests back to the client.

I think for now we should log a warning when someone does this, or perhaps have a "strict" flag that throws an error?

### LINKED ISSUE #137: Remove `.editorconfig` from the mcp-lite templates
Create mcp lite uses the templates in the `templates/` dir and some of those have a `.editorconfig` file. I don't like it. We shouldn't enforce those rules on other people (esp usage of tabs vs spaces)

### PR DESCRIPTION
**Pull request by laulauland**
This PR addresses multiple GitHub issues with improvements to the mcp-lite core library:

### DNS Rebinding Protection Documentation (#137)
- Added documentation section in README.md explaining DNS rebinding protection
- Included code examples for configuring `allowedHosts` and `allowedOrigins`

### Multiple Binding Warning (#99)
- Added `boundServers` WeakSet to track which servers have been bound
- Added warning when binding the same HTTP transport to the same server multiple times
- Helps prevent issues with stateful servers

### JSON-RPC Error Responses for Validation (#98)
- Changed Host/Origin validation failures to return proper JSON-RPC error responses
- Returns 403 status with structured error instead of plain text

### Schema Projection Logging (#96)
- Added configurable logger option to `McpServerOptions`
- Logger defaults to stderr (console.error) for all log levels for better visibility
- Schema projection warnings are logged for dropped properties, unsupported formats, and non-string enum values
- Users can provide custom logger or disable logging entirely
- Helps developers understand why their schemas are being modified during projection

### Remove PING Notification (#86)
- Removed automatic PING notification from GET SSE stream
- Added SSE comment (`: stream ready`) to properly establish connection without sending JSON-RPC data
- Updated all integration tests to reflect removal of PING event
- Verified compatibility with SSE specification

## Testing
All 188 integration tests passing. Updated test expectations to account for removal of PING notification and logger changes.

## Closes
Closes #137
Closes #99
Closes #98
Closes #96
Closes #86

### CODE REVIEW

**Comment by laulauland** [comment]
@codex review this please

File: packages/core/src/context.ts [hunk 1]
```diff
@@ -22,6 +22,10 @@ import {
   toElicitationRequestedSchema,
 } from "./validation.js";
 
+interface Logger {
```
Comment (brettimus) [inline packages/core/src/context.ts]: we already have a logger interface defined in `packages/core/src/core.ts`, this one seems like a straggler

File: packages/core/src/transport-http/transport-http.ts [hunk 2]
```diff
@@ -206,7 +207,17 @@ export class StreamableHttpTransport {
     request: Request,
     options?: { authInfo?: AuthInfo },
   ) => Promise<Response> {
+    // Check if this server has already been bound to a transport
+    if (this.boundServers.has(server)) {
+      console.warn(
+        "[mcp-lite] WARNING: Binding an HTTP transport multiple times to the same server can break stateful servers. " +
```
Comment (brettimus) [inline packages/core/src/transport-http/transport-http.ts:215]: did biome stop complaining about string concatenation with `+`? it always hates when llms do this

File: packages/core/src/transport-http/transport-http.ts [hunk 3]
```diff
@@ -206,7 +207,17 @@ export class StreamableHttpTransport {
     request: Request,
     options?: { authInfo?: AuthInfo },
   ) => Promise<Response> {
+    // Check if this server has already been bound to a transport
+    if (this.boundServers.has(server)) {
+      console.warn(
```
Comment (brettimus) [inline packages/core/src/transport-http/transport-http.ts:214]: this is using `console` fwiw, not the logger

File: packages/core/src/core.ts [hunk 4]
```diff
@@ -310,7 +320,13 @@ export class McpServer {
...
     };
     this.schemaAdapter = options.schemaAdapter;
-    this.logger = options.logger || console;
+    // Default logger writes all messages to stderr for better visibility
+    this.logger = options.logger || {
+      error: console.error,
+      warn: console.error,
+      info: console.error,
+      debug: console.error,
+    };
```
Comment (brettimus) [inline packages/core/src/core.ts]: i don't think we should do this. 

either no-op the noisier levels by default or switch back to "console-by-default" 

some reasoning here: `stderr` is semantically treated as errors (by downstream tooling). you don't want to treat debug logs as errors.

Comment (brettimus) [reply packages/core/src/core.ts]: there is another take that libraries should be quiet by default and enable verbose logging easily, not sure how you feel about that apporach instead

File: packages/core/src/sse-writer.ts [hunk 5]
```diff
@@ -45,6 +46,14 @@ export function createSSEStream(options?: { onClose?: () => void }): {
         end();
       }
     },
+    writeComment(comment: string): void {
```
Comment (brettimus) [inline packages/core/src/sse-writer.ts:49]: how do clients treat this? do they freak out at non-jsonrpc messages? are we allowed to send just random events down the sse stream that have no bearing on the messages back and forth between client and server?

Comment (brettimus) [reply packages/core/src/sse-writer.ts:49]: nvm i see the comment below in the code addressing this

File: packages/core/src/transport-http/transport-http.ts [hunk 6]
```diff
@@ -796,11 +833,17 @@ export class StreamableHttpTransport {
     // Register the session stream
     this.sessionStreams.set(sessionId, writer);
 
+    // Send an SSE comment to establish the connection
+    // SSE streams need some initial data to properly establish the connection with the client.
+    // Without this, the client's SSE reader may not recognize the stream as "open" and will wait
+    // indefinitely for the first event. Comments (lines starting with ':') are part of the SSE spec
+    // and are ignored by clients but still flush the response and signal the stream is active.
+    // This is equivalent to Node.js's res.flushHeaders() but works in Fetch API environments.
```
Comment (brettimus) [inline packages/core/src/transport-http/transport-http.ts:843]: good solution!

File: packages/core/src/validation.ts [hunk 7]
```diff
@@ -103,9 +103,14 @@ interface ElicitationJsonSchema {
   additionalProperties?: boolean;
 }
 
+interface Logger {
```
Comment (brettimus) [inline packages/core/src/validation.ts]: again, feel like we could rely on the logger interface we export instead of this rogue one

File: templates/starter-mcp-cloudflare/.editorconfig
Comment (brettimus) [inline templates/starter-mcp-cloudflare/.editorconfig:1]: 🗑️

**Review by brettimus — APPROVED** [review]
pre-approval but please fix the "everything to stderr" default, as i don't think that's a sensible default for a library to have

if anything do "quiet by default" for debug / info logs

or just revert to use console

**Comment by laulauland** [comment]
Updated to make the logger **completely silent** by default (all levels are no-ops, including error and warn).

Now, like other parts of mcp-lite, logging follows the adapter pattern - you opt-in when you need it. I feel like this is cleaner than having error/warn go to console by default. This way the library is completely silent unless the user explicitly enables logging.

Users can easily enable logging by providing a logger:
```typescript
const mcp = new McpServer({
  name: "my-server",
  version: "1.0.0",
  logger: {
    error: console.error,
    warn: console.warn,
    info: console.info,
    debug: console.debug,
  }
});
```

Noted this in the README docs with examples for various logging configurations.

**Comment by laulauland** [comment]
CI is failing but this is just `pkg.pr.new` bugging out
